import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href='/reviews'>
        <div style={{ padding: '100px', margin: '50px', width: '50px', height: '50px', cursor: 'pointer' }}>
          <a style={{ color: 'white', padding: '100px', width: '50px', height: '50px', fontFamily: 'futura' }}> reviews</a>
        </div>
      </Link>

    </div >
  )
}
